<?php
// Heading
$_['heading_title']                = 'Indstillinger';

// Text
$_['text_success']                 = 'Succes: Du har &aelig;ndret indstillingerne!';
$_['text_items']                   = 'Varer';
$_['text_product']                 = 'Produkter';
$_['text_voucher']                 = 'V&aelig;rdikuponer';
$_['text_tax']                     = 'Skatter';
$_['text_account']                 = 'Konto';
$_['text_checkout']                = 'Checkout';
$_['text_stock']                   = 'Lager';
$_['text_affiliate']               = 'Affiliates';
$_['text_return']                  = 'Returneringer';
$_['text_image_manager']           = 'Billede h&aring;ndtering';
$_['text_browse']                  = 'Gennemse';
$_['text_clear']                   = 'Ryd';
$_['text_shipping']                = 'Forsendelses adresse';
$_['text_payment']                 = 'Betalingsadresse';
$_['text_mail']                    = 'Mail';
$_['text_smtp']                    = 'SMTP';

// Entry
$_['entry_name']                   = 'Butiksnavn:';
$_['entry_owner']                  = 'Butiksejer:';
$_['entry_address']                = 'Adresse:';
$_['entry_email']                  = 'E-Mail:';
$_['entry_telephone']              = 'Telefon:';
$_['entry_fax']                    = 'Fax:';
$_['entry_title']                  = 'Titel:';
$_['entry_meta_description']       = 'Meta Tag Description:';
$_['entry_layout']                 = 'Standard layout:';
$_['entry_template']               = 'Template:';
$_['entry_country']                = 'Land:';
$_['entry_zone']                   = 'Region / Stat:';
$_['entry_language']               = 'Sprog:';
$_['entry_admin_language']         = 'Administrations sprog:';
$_['entry_currency']               = 'Valuta:<br /><span class="help">Ret standard valutaen. T&oslash;m din browsers cache for se &aelig;ndringerne og nulstil din nuv&aelig;rende cookie.</span>';
$_['entry_currency_auto']          = 'Auto opdater valuta:<br /><span class="help">S&aelig;t butikken til automatisk at dagligt opdatere valutaer.</span>';
$_['entry_length_class']           = 'L&aelig;ngde klasse:';
$_['entry_weight_class']           = 'V&aelig;gt klasse:';
$_['entry_catalog_limit'] 	       = 'Standard varer per side (Katalog):<br /><span class="help">Afg&oslash;r hvor mange katalog varer der vises per side (produkter, kategorier, osv)</span>';
$_['entry_admin_limit']   	       = 'Standard varer per side (Admin):<br /><span class="help">Afg&oslash;r hvor mange admin varer der vises per side (produkter, kategorier, osv)</span>';
$_['entry_product_count']          = 'Kategori produkt t&aelig;ller:<br /><span class="help">Viser antallet af produkter inde i underkategorierne i webshoppen hovedkategori menu. V&aelig;r opm&aelig;rksom p&aring; at dette vil foresage en ekstrem perfomance nedgang for butikker med mange underkategorier!</span>';
$_['entry_review']       	       = 'Tillad anmeldelser:<br /><span class="help">Aktiver/deaktiver nye anmeldelser og visning af eksisterende anmeldelser.</span>';
$_['entry_download']               = 'Tillad downloads:';
$_['entry_voucher_min']            = 'V&aelig;rdikupon minimum:<br /><span class="help">Minimum bel&oslash;b kunder kan k&oslash;be v&aelig;rdikuponer for.</span>';
$_['entry_voucher_max']            = 'V&aelig;rdikupon maksimum:<br /><span class="help">Maksimum bel&oslash;b kunder kan k&oslash;be v&aelig;rdikuponer for.</span>';
$_['entry_tax']                    = 'Vis priser med moms:';
$_['entry_vat']                    = 'Valider CVR/VAT numre:<br /><span class="help">Valider CVR/VAT nummre via http://ec.europa.eu service.</span>';
$_['entry_tax_default']            = 'Brug butikkens moms adresse:<br /><span class="help">Brug butikkens addresse til at beregne moms hvis kunden ikke er logget ind. Du kan v&aelig;lge at bruge butikkens adresse for kundernes leverings eller betalings adresse.</span>';
$_['entry_tax_customer']           = 'Brug kundens moms adresse:<br /><span class="help">Brug kundens angivede standard adresse n&aring;r de logger ind til at beregne moms. Du kan v&aelig;lge at bruge standard adressen for kundernes leverings eller betalings adresse.</span>';
$_['entry_customer_online']        = 'Kunder online:<br /><span class="help">Track kunder online via kunde statistik sektionen.</span>';
$_['entry_customer_group']         = 'Kunde gruppe:<br /><span class="help">Standard kunde gruppe.</span>';
$_['entry_customer_group_display'] = 'Kunde grupper:<br /><span class="help">Vis kunde grupper som nye kunder kan tilmelde sig som eksempelvis VIP eller engros.</span>';
$_['entry_customer_price']         = 'Login viser priser:<br /><span class="help">Vis kun priser hvis kunden er logget ind.</span>';
$_['entry_account']                = 'Konto betingelser:<br /><span class="help">Tvinger kunder til at acceptere betingelserne for en konto kan oprettes.</span>';
$_['entry_cart_weight']            = 'Vis kurvens v&aelig;gt:<br /><span class="help">Viser indk&oslash;bskurvens v&aelig;gt.</span>';
$_['entry_guest_checkout']         = 'Guest Checkout:<br /><span class="help">Allow customers to checkout without creating an account. This will not be available when a downloadable product is in the shopping cart.</span>';
$_['entry_checkout']               = 'Checkout Terms:<br /><span class="help">Forces people to agree to terms before an a customer can checkout.</span>';
$_['entry_order_edit']             = 'Order Editing:<br /><span class="help">Number of days allowed to edit an order. This is required because prices and discounts may change over time corrupting the order if it\'s edited.</span>';
$_['entry_invoice_prefix']         = 'Invoice Prefix:<br /><span class="help">Set the invoice prefix (e.g. INV-2011-00). Invoice ID\'s will start at 1 for each unique prefix</span>';
$_['entry_order_status']           = 'Order Status:<br /><span class="help">Set the default order status when an order is processed.</span>';
$_['entry_complete_status']        = 'Complete Order Status:<br /><span class="help">Set the order status the customers order must reach before they are allowed to access their downloadable products and gift vouchers.</span>';
$_['entry_stock_display']          = 'Display Stock:<br /><span class="help">Display stock quantity on the product page.</span>';
$_['entry_stock_warning']          = 'Show Out Of Stock Warning:<br /><span class="help">Display out of stock message on the shopping cart page if a product is out of stock but stock checkout is yes. (Warning always shows if stock checkout is no)</span>';
$_['entry_stock_checkout']         = 'Stock Checkout:<br /><span class="help">Allow customers to still checkout if the products they are ordering are not in stock.</span>';
$_['entry_stock_status']           = 'Out of Stock Status:<br /><span class="help">Set the default out of stock status selected in product edit.</span>';
$_['entry_affiliate']              = 'Affiliate Terms:<br /><span class="help">Forces people to agree to terms before an affiliate account can be created.</span>';
$_['entry_commission']             = 'Affiliate Commission (%):<br /><span class="help">The default affiliate commission percentage.</span>';
$_['entry_return']                 = 'Return Terms:<br /><span class="help">Forces people to agree to terms before an return account can be created.</span>';
$_['entry_return_status']          = 'Return Status:<br /><span class="help">Set the default return status when an returns request is submitted.</span>';
$_['entry_logo']                   = 'Store Logo:';
$_['entry_icon']                   = 'Icon:<br /><span class="help">The icon should be a PNG that is 16px x 16px.</span>';
$_['entry_image_category']         = 'Category Image Size:';
$_['entry_image_thumb']            = 'Product Image Thumb Size:';
$_['entry_image_popup']            = 'Product Image Popup Size:';
$_['entry_image_product']          = 'Product Image List Size:';
$_['entry_image_additional']       = 'Additional Product Image Size:';
$_['entry_image_related']          = 'Related Product Image Size:';
$_['entry_image_compare']          = 'Compare Image Size:';
$_['entry_image_wishlist']         = 'Wish List Image Size:';
$_['entry_image_cart']             = 'Cart Image Size:';
$_['entry_ftp_host']               = 'FTP Host:';
$_['entry_ftp_port']               = 'FTP Port:';
$_['entry_ftp_username']           = 'FTP Username:';
$_['entry_ftp_password']           = 'FTP Password:';
$_['entry_ftp_root']               = 'FTP Root:<span class="help">The directory your opencart installation is stored in normally \'public_html/\'.</span>';
$_['entry_ftp_status']             = 'Enable FTP:';
$_['entry_mail_protocol']          = 'Mail Protocol:<span class="help">Only choose \'Mail\' unless your host has disabled the php mail function.</span>';
$_['entry_mail_parameter']         = 'Mail Parameters:<span class="help">When using \'Mail\', additional mail parameters can be added here (e.g. "-femail@storeaddress.com").</span>';
$_['entry_smtp_host']              = 'SMTP Host:';
$_['entry_smtp_username']          = 'SMTP Username:';
$_['entry_smtp_password']          = 'SMTP Password:';
$_['entry_smtp_port']              = 'SMTP Port:';
$_['entry_smtp_timeout']           = 'SMTP Timeout:';
$_['entry_account_mail']           = 'New Account Alert Mail:<br /><span class="help">Send a email to the store owner when a new account is registered.</span>';
$_['entry_alert_mail']             = 'New Order Alert Mail:<br /><span class="help">Send a email to the store owner when a new order is created.</span>';
$_['entry_alert_emails']           = 'Additional Alert E-Mails:<br /><span class="help">Any additional emails you want to receive the alert email, in addition to the main store email. (comma separated)</span>';
$_['entry_fraud_detection']        = 'Use MaxMind Fraud Detection System:<br /><span class="help">MaxMind is a fraud detections service. If you don\'t have a license key you can <a href="http://www.maxmind.com/?rId=opencart" target="_blank"><u>sign up here</u></a>. Once you have obtained a key copy and paste it into the field below.</span>';
$_['entry_fraud_key']              = 'MaxMind License Key:</span>';
$_['entry_fraud_score']            = 'MaxMind Risk Score:<br /><span class="help">The higher the score the more likly the order is fraudulent. Set a score between 0 - 100.</span>';
$_['entry_fraud_status']           = 'MaxMind Fraud Order Status:<br /><span class="help">Orders over your set score will be assigned this order status and will not be allowed to reach the complete status automatically.</span>';
$_['entry_secure']                 = 'Use SSL:<br /><span class="help">To use SSL check with your host if a SSL certificate is installed and added the SSL URL to the catalog and admin config files.</span>';
$_['entry_shared']                 = 'Use Shared Sessions:<br /><span class="help">Try to share the session cookie between stores so the cart can be passed between different domains.</span>';
$_['entry_robots']                 = 'Robots:<br /><span class="help">A list of web crawler user agents that shared sessions will not be used with. Use separate lines for each user agent.</span>';
$_['entry_seo_url']                = 'Use SEO URL\'s:<br /><span class="help">To use SEO URL\'s apache module mod-rewrite must be installed and you need to rename the htaccess.txt to .htaccess.</span>';
$_['entry_file_extension_allowed'] = 'Allowed File Extensions:<br /><span class="help">Add which file extensions are allowed to be uploaded. Use a new line for each value.</span>';
$_['entry_file_mime_allowed']      = 'Allowed File Mime Types:<br /><span class="help">Add which file mime types are allowed to be uploaded. Use a new line for each value.</span>';
$_['entry_maintenance']            = 'Maintenance Mode:<br /><span class="help">Prevents customers from browsing your store. They will instead see a maintenance message. If logged in as admin, you will see the store as normal.</span>';
$_['entry_password']               = 'Allow Forgotten Password:<br /><span class="help">Allow forgotten password to be used for the admin. This will be disabled automatically if the system detects a hack attempt.</span>';
$_['entry_encryption']             = 'Encryption Key:<br /><span class="help">Please provide a secret key that will be used to encrypt private information when processing orders.</span>';
$_['entry_compression']            = 'Output Compression Level:<br /><span class="help">GZIP for more efficient transfer to requesting clients. Compression level must be between 0 - 9</span>';
$_['entry_error_display']          = 'Display Errors:';
$_['entry_error_log']              = 'Log Errors:';
$_['entry_error_filename']         = 'Error Log Filename:';
$_['entry_google_analytics']       = 'Google Analytics Code:<br /><span class="help">Login to your <a href="http://www.google.com/analytics/" target="_blank"><u>Google Analytics</u></a> account and after creating your web site profile copy and paste the analytics code into this field.</span>';

// Error
$_['error_warning']                = 'Warning: Please check the form carefully for errors!';
$_['error_permission']             = 'Warning: You do not have permission to modify settings!';
$_['error_name']                   = 'Store Name must be between 3 and 32 characters!';
$_['error_owner']                  = 'Store Owner must be between 3 and 64 characters!';
$_['error_address']                = 'Store Address must be between 10 and 256 characters!';
$_['error_email']                  = 'E-Mail Address does not appear to be valid!';
$_['error_telephone']              = 'Telephone must be between 3 and 32 characters!';
$_['error_title']                  = 'Title must be between 3 and 32 characters!';
$_['error_limit']       	       = 'Limit required!';
$_['error_customer_group_display'] = 'You must include the default customer group if you are going to use this feature!';
$_['error_voucher_min']            = 'Minimum voucher amount required!';
$_['error_voucher_max']            = 'Maximum voucher amount required!';
$_['error_image_thumb']            = 'Product Image Thumb Size dimensions required!';
$_['error_image_popup']            = 'Product Image Popup Size dimensions required!';
$_['error_image_product']          = 'Product List Size dimensions required!';
$_['error_image_category']         = 'Category List Size dimensions required!';
$_['error_image_additional']       = 'Additional Product Image Size dimensions required!';
$_['error_image_related']          = 'Related Product Image Size dimensions required!';
$_['error_image_compare']          = 'Compare Image Size dimensions required!';
$_['error_image_wishlist']         = 'Wish List Image Size dimensions required!';
$_['error_image_cart']             = 'Cart Image Size dimensions required!';
$_['error_ftp_host']               = 'FTP Host required!';
$_['error_ftp_port']               = 'FTP Port required!';
$_['error_ftp_username']           = 'FTP Username required!';
$_['error_ftp_password']           = 'FTP Password required!';
$_['error_error_filename']         = 'Error Log Filename required!';
$_['error_encryption']             = 'Encryption must be between 3 and 32 characters!';
?>
